"""
Migration runner for the cic-mcp-session Postgres schema.

Job: session-schema-migration-tooling-001

Before this job, the 6 SQL files under output/ (session-postgres-schema.sql
and the 5 *-migration.sql files) had to be applied BY HAND, in a specific
order that existed only as documentation (file-header comments, job
completion timestamps in jobs/index.yaml). There was no schema-version
table, no machine-enforced order, no idempotent re-apply, and no checksum
protection against an already-applied migration being silently edited.

This module formalizes that manual process WITHOUT touching the content of
the 6 original files. The files are copied (not moved -- see
output/session-schema-migration-tooling.md "Decisions Proposed" for why the
output/ originals are kept) into migrations/, renamed with a zero-padded
sequence prefix that encodes the exact order that was already being
followed:

    migrations/0001_postgres_schema.sql      <- output/session-postgres-schema.sql
    migrations/0002_chunk_indexer.sql        <- output/session-chunk-indexer-migration.sql
    migrations/0003_retrieval_quality.sql    <- output/session-retrieval-quality-migration.sql
    migrations/0004_vector_search_api.sql    <- output/session-vector-search-api-migration.sql
    migrations/0005_hybrid_search_api.sql    <- output/session-hybrid-search-api-migration.sql
    migrations/0006_source_refs_api.sql      <- output/session-source-refs-api-migration.sql

No external migration framework (Alembic, Flyway) is introduced. The schema
here is 6 flat, hand-written, mostly-additive SQL files (5 of the 6 are
single-purpose ALTER/CREATE OR REPLACE FUNCTION migrations against a single
base schema) with no branching migration history and no need for
autogenerated diffing against ORM models (this codebase has no ORM layer --
see session_store/envelope_writer.py and friends, which hand-write SQL via
psycopg). A ~150-line apply-in-order-with-checksum runner covers the actual
requirement; Alembic's revision-graph/branching machinery and Flyway's JVM
dependency would add operational surface this project does not need.

Design:

- schema_migrations.applied (version TEXT PK, filename TEXT, checksum TEXT,
  applied_at TIMESTAMPTZ) is the single source of truth for "what has been
  applied." It is created by this module on first run (not by a migration
  file in migrations/), via CREATE SCHEMA IF NOT EXISTS / CREATE TABLE IF
  NOT EXISTS, so that a brand-new, completely empty database can bootstrap
  itself with zero pre-existing state.
- version is the sequence prefix ("0001", "0002", ...), NOT the filename,
  so that a future rename of the descriptive suffix does not break checksum
  lookups keyed by version.
- checksum is sha256 of the migration file's exact byte content. If a
  migration that is already recorded in schema_migrations.applied is found
  on disk with a DIFFERENT checksum than what was recorded, run_migrations()
  raises ChecksumMismatchError and applies NOTHING further in that run --
  this is a hard stop, not a warning, per this job's Forbidden Shortcuts
  ("checksum-ellenorzes kihagyasa vagy csendes felulirasa eltero checksum
  eseten").
- Migrations are applied in version order; a migration is skipped (not
  re-run) if its version is already present in schema_migrations.applied
  AND its checksum matches -- this is the idempotent re-apply path proven
  in output/session-schema-migration-tooling.md "Findings" /
  tests/test_session_store/test_migrate.py.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path

import psycopg

from session_store.envelope_writer import SessionStoreConfig

MIGRATIONS_DIR = Path(__file__).resolve().parent.parent / "migrations"

_FILENAME_RE = re.compile(r"^(\d{4})_.*\.sql$")


class ChecksumMismatchError(RuntimeError):
    """Raised when an already-applied migration's on-disk content has changed."""


@dataclass(frozen=True)
class Migration:
    version: str  # zero-padded sequence, e.g. "0001"
    filename: str  # e.g. "0001_postgres_schema.sql"
    path: Path
    checksum: str  # sha256 hex digest of the file's exact byte content
    sql_text: str


def _sha256_of(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def discover_migrations(migrations_dir: Path = MIGRATIONS_DIR) -> list[Migration]:
    """Read every *.sql file in migrations_dir, sorted by sequence prefix.

    Raises ValueError if a file in the directory does not match the
    `NNNN_description.sql` naming convention, or if two files share the
    same sequence prefix (ambiguous order).
    """
    migrations: list[Migration] = []
    seen_versions: dict[str, str] = {}
    for path in sorted(migrations_dir.glob("*.sql")):
        match = _FILENAME_RE.match(path.name)
        if not match:
            raise ValueError(
                f"migration file {path.name!r} does not match the required "
                "NNNN_description.sql naming convention"
            )
        version = match.group(1)
        if version in seen_versions:
            raise ValueError(
                f"duplicate migration version {version!r}: "
                f"{seen_versions[version]!r} and {path.name!r}"
            )
        seen_versions[version] = path.name
        data = path.read_bytes()
        migrations.append(
            Migration(
                version=version,
                filename=path.name,
                path=path,
                checksum=_sha256_of(data),
                sql_text=data.decode("utf-8"),
            )
        )
    migrations.sort(key=lambda m: m.version)
    return migrations


def _ensure_tracking_table(conn: psycopg.Connection) -> None:
    conn.execute("CREATE SCHEMA IF NOT EXISTS schema_migrations")
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS schema_migrations.applied (
            version     TEXT PRIMARY KEY,
            filename    TEXT NOT NULL,
            checksum    TEXT NOT NULL,
            applied_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )


def _already_applied(conn: psycopg.Connection) -> dict[str, str]:
    """Return {version: checksum} for every row currently in the tracking table."""
    rows = conn.execute(
        "SELECT version, checksum FROM schema_migrations.applied"
    ).fetchall()
    return {version: checksum for version, checksum in rows}


def run_migrations(
    config: SessionStoreConfig | None = None,
    migrations_dir: Path = MIGRATIONS_DIR,
) -> list[str]:
    """Apply every not-yet-applied migration in migrations_dir, in order.

    Returns the list of versions actually applied during this call (empty
    list means a full no-op -- every discovered migration was already
    recorded with a matching checksum).

    Raises ChecksumMismatchError, WITHOUT applying anything further in this
    call, if any already-applied migration's on-disk checksum no longer
    matches the checksum recorded at the time it was applied.
    """
    cfg = config or SessionStoreConfig.from_env()
    migrations = discover_migrations(migrations_dir)

    applied_versions: list[str] = []
    with psycopg.connect(cfg.conninfo(), autocommit=False) as conn:
        _ensure_tracking_table(conn)
        conn.commit()

        recorded = _already_applied(conn)

        # Checksum verification pass FIRST, over ALL recorded migrations,
        # before applying anything new in this call -- a tampered
        # already-applied migration must hard-stop the run, not be
        # discovered halfway through applying later migrations.
        for migration in migrations:
            if migration.version in recorded:
                recorded_checksum = recorded[migration.version]
                if recorded_checksum != migration.checksum:
                    raise ChecksumMismatchError(
                        f"migration {migration.filename!r} (version "
                        f"{migration.version!r}) has checksum "
                        f"{migration.checksum!r} on disk but was recorded "
                        f"with checksum {recorded_checksum!r} when "
                        "originally applied -- the file was modified after "
                        "being applied. Refusing to run any further "
                        "migrations in this call."
                    )

        for migration in migrations:
            if migration.version in recorded:
                continue  # already applied, checksum verified above: no-op
            with conn.cursor() as cur:
                cur.execute(migration.sql_text)  # type: ignore[arg-type]
                cur.execute(
                    """
                    INSERT INTO schema_migrations.applied
                        (version, filename, checksum)
                    VALUES (%s, %s, %s)
                    """,
                    (migration.version, migration.filename, migration.checksum),
                )
            conn.commit()
            applied_versions.append(migration.version)

    return applied_versions


def main() -> None:  # pragma: no cover - thin CLI wrapper
    applied = run_migrations()
    if applied:
        print(f"Applied {len(applied)} migration(s): {', '.join(applied)}")
    else:
        print("No pending migrations. Database is up to date.")


if __name__ == "__main__":  # pragma: no cover
    main()
